### ISSUE TITLE
Adding support for multiple image formats (.dcm etc) in dataloaders

### ISSUE THREAD

**Issue by MohitTare** [perone/medicaltorch#14]
I was looking into another popular Tensorflow based medical library implementation [NiftyNet](https://niftynet.readthedocs.io/en/dev/index.html) , specifically the dataloaders and really liked the idea of multiple [image loaders](https://niftynet.readthedocs.io/en/dev/niftynet.io.image_loader.html) . Any plans on implementing the same ? 

As an initial guess we can dynamically pass the various functions for loading image formats in the input_handle and gt_handle

`self.input_handle = nib.load(self.input_filename)`
`self.gt_handle = nib.load(self.gt_filename)`

We may need to make some changes as i saw that the slicing functionality depends on the nibabel/nifty format. I can start of the implementation if you are fine and may be later we can review.

If you have any further ideas, i can help over the same.

Thanks,
Mohit

**Comment by farazkhan86** [comment]
@MohitTare 

I completely agree with your request. Adding support for additional image formats will greatly help.

Were you able to make any progress with the implementation of adding additional image format support? As it would be really helpful if you did.

Thanks

**Comment by perone** [comment]
Support for additional images can be easily implemented and I complete agree with that, but for DICOM for instance we shouldn't support it because they are not efficient and there are many tools to convert from DICOM to nii files.

**Comment by MohitTare** [comment]
@perone  Yes I was actually trying to solve a problem using DICOM and found couple of discussions on web stating to convert DICOM to NIFTI. NIFTI is certainly more efficient. I converted DICOM to NIFTI using the [dcm2nii](https://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.interfaces.dcm2nii.html)
and then built further workflow using NIFTI

**Comment by perone** [comment]
Thanks for the feedback @MohitTare !
