### ISSUE TITLE
3D Transformations?

### ISSUE THREAD

**Issue by aydindemircioglu** [perone/medicaltorch#20]
are 3D transformations supported?
it is not clear to my from the documentation and examples,
and from looking at the code i'd guess its not the case?
if they are, could you update the docs?
if not, is anyone working on it? 
(maybe i'll add some basic transformations)

**Comment by morvan-s** [comment]
It doesn't seem that 3D transformations are supported.
I'm currently working on a 3DUnet project and I have updated my local medicaltorch (adding classes like MRI3DSegmentationDataset). I'm going to implement some transformations for my project in the 2 next weeks and will probably try to make a pull request to add these methods.
