### ISSUE TITLE
Notebook in "Getting started" page does not open

### ISSUE THREAD

**Issue by omendezmorales** [perone/medicaltorch#22]
Hello, 
I tried to open the notebook indicated in the _[Getting Started](https://medicaltorch.readthedocs.io/en/stable/getstarted.html)_ page, but I get the following error in the Collab website:
Notebook loading error

> There was an error loading this notebook. Ensure that the file is accessible and try again.
> Failed to execute 'json' on 'Response': body stream is locked

I'm using the [_Brave_](https://support.brave.com/hc/en-us) browser under Linux, if that helps. Thanks!

**Comment by perone** [comment]
I think it might be something related to your environment because I just tried now and it is working fine.

**Comment by omendezmorales** [comment]
> I think it might be something related to your environment because I just tried now and it is working fine.

Hi @perone ,
Indeed, I tried with another and worked. Apologies for the false alarm.

**Comment by perone** [comment]
No problem, glad you solved.
