### ISSUE TITLE
Medical image type

### ISSUE THREAD

**Issue by Yifeifr** [perone/medicaltorch#7]
Hello,

Thanks for your work!
I have a question about the type of medical images, generally they were collected in dicom type(.dcm), do you create any dataloaders for dicom type inputs? As I know, there is a python library for such image type, it was used to convert .dcm to numpy, do you use it?

**Comment by perone** [comment]
Hi @Yifeifr, we support NIfTI files only for the moment, we might support dicom in the future, but since you can easily convert them to NIfTI. I always find NIfTI files much better to work with.

**Comment by Yifeifr** [comment]
Great, thanks for your reply.
